### PR TITLE
Automatic firmware homing support for the Cupcake (On the ReplicatorG side)

### PR DESCRIPTION
**Pull request by Winter-Guerra**
I also sent you an email with a link to my repo and a quick rundown of what I did. Hope you like it!

-Winter

Update: Just changed the subject of the pull, now it is more of a subject.

### CODE REVIEW

**Comment by Winter-Guerra** [comment]
Actually can you push this back a little? I'm currently working on integrating support for odd endstop configurations and Zaggo's Z-probe hardware. I'm even going to try to see if I can make a step by step GUI to tell people how to configure it. Thanks!

-Winter

**Comment by phooky** [comment]
Sure, just let me know when you're ready to go with this.

**Comment by phooky** [comment]
Hey, Winter, what's the status on this?  Are you ready to integrate?

**Comment by Winter-Guerra** [comment]
Hello Adam, sorry about opening up this pull request and then realizing that it needed some changes, here is where I am right now:

-Automatic homing on all 3 axis with arbitrary endstops configurations (tested and working.)
-Java Gui (90% there but untested with a 'bot, today I will test my code with the school makerbot to see if it works)
-Zaggo Z-Probe hardware support (Supported in the Gui, but not in the MB firmware yet. It's what I am going to add today after making sure that what I have now works.)

An estimate on when can I get this done might be Friday or Tuesday (Those days I have access to a Makerbot for a few minutes so I can check that everything is working before submitting)

Again sorry about this pull request, I got a bit ahead of myself....
-Winter

**Comment by phooky** [comment]
Hey!  Good to hear from you.  I'd love to get this stuff in before we start shipping thingomatics, which is still a couple of weeks away.

There's been a lot of messing around in the guts of repG lately, so merges may be tricky.  Let me know if you need a hand.

Thanks,
-a

**Comment by Winter-Guerra** [comment]
Hello Adam,
Just letting you know that I haven't forgotten about this. Everything is done but some merge conflicts and recent additions of mine since earlier today(exception handlers) have convinced me to test everything tomorrow before giving you the final go ahead.
Hope you had a great thanksgiving weekend!

**Comment by Winter-Guerra** [comment]
Done! This now all works and has been ported to the latest version of the Makerbot/ReplicatorG firmware/software so merging should be a breeze. Here is a quick bullet-point of everything that I did:

-All homing functions other than the one I have just made have been moved to the "Legacy Homing" menu in the ReplicatorG setup window.
-Added a new menu titled Automatic Homing with the options to home and setup homing.
-Added a "pause" boolean to the extruder temperature graph (it sometimes tried to send commands overlapping with commands to home)
-Added a new write 32bit int to Makerbot EEPROM command in both sides of the firmware (I know that there is a way to do this without adding a new command, but I couldn't figure it out.)
-Added a new file "LinearScripts.cc" to the firmware to handle all of my code.
-Added a gui that allows the user to select and define all of the things needed for homing (in the setup option)
-It now supports the option to home using Zaggo's Z-Probe hardware while connected to pin D10 on the extruder. (Pin D10 as not to interfere with Unicorns)
-Added a new GCode to ReplicatorG that is used in the start.txt: M138 (Go Home!)

Hope you like it!

-Winter

Ps: Sorry it took so long to finish this.....

**Comment by phooky** [comment]
Hey Winter!

Time is actually very tight here and I'm trying to get a release together.  Can you give me a high-level view of exactly what this patch introduces?  I need to make a decision about integrating this in the next twenty hours or so.

-a

**Comment by Winter-Guerra** [comment]
Ok here is a general description (Warning, this is a long post!):

My patch adds support for automatic homing of the Makerbot using only 1 line of Gcode instead of the current method which involves playing with a bunch of lines of Gcode. When my homing Gcode is placed at the beginning of the start Gcodes, it sends one command to the Makerbot to start homing from settings saved in EEPROM (The computer does not send or save any settings).This means homing setup is easier now because I've created a setup GUI in ReplicatorG that asks the user for everything required by the Makerbot to home. Things like what endstops are installed, and how many mm should the nozzle lift before attempting to home (to avoid hitting the bolts or walls around the build platform. This lift is also needed to use Zaggo's Z-Probe hardware but more on that later.) The GUI then prompts the user to center the Makerbot's axis to absolute zero (the nozzle a hair above the build platform, with both XY centered) before starting a calibration routine embedded in the Makerbot firmware that measures the various distances to the endstops and saves them in EEPROM (it does all of this in a safe way that will not dig a hole in the BP). After setting up the bot once, the Makerbot permanently knows how to find it's way back to 0,0,0 even if you use different computers, turn the bot on and off or fiddle with axis positions. Also if you make any changes to the homing settings on the Makerbot it does not require reskeinings of all your skeined prints since all of the settings required for homing are stored on the bot. Even better yet, Zaggo, invented a way of using a endstop and a servo connected to the Extruder board, to find the exact hight of the build platform, even if you hot swap your flat build platform for a towering ABP. This means that you can (if you install a servo and endstop), hot swap different build surfaces without having to touch any settings because the 'bot will compensate by finding the current exact height. The user only needs to install the hardware, check the “Zaggo Z-Probe hardware installed” checkbox in the setup GUI, enter the desired servo angles for the engaged and disengaged servo positions, test them if they want (there is a test button) and click commit. Take a look at http://pleasantsoftware.com/developer/3d/page/2/ (Zaggo's blog) if you want a video of how his works (his script is still in Gcode and works differently then mine, but may give you a better idea of what I'm talking about) or just ask me what else you want to know.

Ok, that post was a mouthful but please tell me if you need anything else. Good luck with the release!

-Winter

**Comment by Winter-Guerra** [comment]
Sorry, but I forgot to say that you do not need Zaggo's Z-Probe hardware installed to home. You can home just using 3 endstops but you don't have the ability to automatically compensate for a swap between a flat platform and a tall abp (hence the "z-probe installed" checkbox)

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Pull request closed without merging**
