### PR TITLE
Skeinlayer problem + better parsable skeinforge 33+ output

### PR DESCRIPTION
**Pull request by ErikDeBruijn**
P.s. make sure you only merge the changes of these two commits, don't merge my ultimaker-stable branch in it's entirety...

### CODE REVIEW

**Comment by phooky** [comment]
Hi Erik;

Could you indicate  which commits we should merge?

I'll look into adding support for multiple firmware update sites so we don't have to merge each other's firmware every time we update.

**Comment by ErikDeBruijn** [comment]
When I have another patch ready for you to pull, I'll definitely let you know. Right now stuff that's ready for merging is merged, thanks again for being open to this really nice cooperation. Though we should more in general think about a roadmap, since I'd like to keep contributing, it would be nice if our updates remain coherent not just at the level of details (it shouldn't just be bugfixes or new features, but the general evolution could be discussed too). Of course we'll have plenty time when I visit you guys for Botacon 0!

B.t.w. I was already merging the XML of our firmwares and yours, but multiple URLs is probably better. It could be part of the machines.xml, I actually started adding firmware links there.

Erik

**Comment by phooky** [comment]
We should address machines.xml as well; right now it's just copying over a version if there's none installed and leaving any existing files, which means existing users won't see new machine descriptors.  I'd like to break this up into multiple files and let them get updated the same way we update firmware xml files.

I'm going to put together a release this week with all the current patches, and get this functionality in next time.

**Comment by phooky** [comment]
I'm going to close this pull request for the moment, since it's kind of out of date.  We're about to blow away sf 33 altogether; we have sf 35 working now and it's a bit better.  We're also adding support material to the options dialog for 35.

**Pull request closed without merging**
