### PR TITLE
RepG STL view: Better UI in MoveTool, constraining Z by holding down shift.

### PR DESCRIPTION
**Pull request by ErikDeBruijn**
I think this really improves the UI of the move tool. Tested on the Mac and Linux with several STLs. Please remove the many debug stuff when you like it and want to merge it upstream. I left it in there so you'll understand my modification more quickly.

### CODE REVIEW

**Comment by kintel** [comment]
I have one comment: Since you chose shift as the modifier, you disabled the use of shift to rotate in e.g. move mode. This is important for people having laptops with only one mouse button (i.e. Macs).

IMO, the correct solution would be to use Ctrl-drag for rotate, as that is the standard way to right-click in Mac OS X. That way, shift could be used as z-axis constrain modifier. However, I cannot get this to work (somehow Ctrl-drags are swallowed somewhere else). If you have any ideas, I'd be happy to test and integrate this.

**Comment by ErikDeBruijn** [comment]
Oh, right! I though there must be a reason why it was implemented the way it was. I just checked an most people have multi-clutch/touch where you can still use two-finger gestures for rotation. 

I could work on Ctrl-drag for rotating the view, for sure.
I found this multi-clutch stuff, btw: 
http://www.glulogic.com/workbench/2009/5/30/java-api-for-mac-trackpad-multitouch-example.html
Would that be worth implementing? :)

**Comment by kintel** [comment]
Two-finger touch is standard for scroll/zoom and that actually works out of the box in ReplicatorG today.

> 2 fingers would only work on recent hardware -> fancy, but not standardized to my knowledge and I'm thus not sure how worthwhile it is to spend time on it.

I think Ctrl-drag would be a good solution for now. Either make it send right-drag events or Ctrl-drag events (which we can handle manually).

**Comment by phooky** [comment]
The whole 3d manipulation interface was a two-week project; it could probably use a total revamp anyway.  Until then, I'm happy with any solution that doesn't involve JNI.

Blender has a fairly intuitive interface for this; "z" puts it in z-constrained mode, "y" in y-constrained, "x" in x-constrained, etc.  It's a little work to implement, though.  I'm just happy to merge whatever works.  :)

**Comment by phooky** [comment]
Putting this aside until there's something that settles the mac interface issue; reopen when ready.

**Pull request closed without merging**
