### PR TITLE
Fixes to Eclipse related files.

### PR DESCRIPTION
**Pull request by derrickoswald**
This makes it slightly easier to set up an Eclipse development environment on Windows.

The changes are basically those that I needed to get it working...
- Fixed updated library miglayout-3.7.4.jar.
- Fixed missing filedrop.jar.

I also added a batch file that creates a soft link allowing debugging within Eclipse.

This is my first try at Git, and ReplicatorG so let me know if something isn't right.
There are also a bunch of warnings about unused variables and dead code that I could clean up if you want.

### CODE REVIEW

**Comment by FarMcKon** [comment]
Excellent,  I'll take a look at these in a bit, and pull them in once I'm solid on what they do.

Awesome stuff, and thanks for contributing!

**Comment by derrickoswald** [comment]
Maybe later.
After a month there's obviously no interest in it.

**Comment by FarMcKon** [comment]
Derrick,
Sorry of the impression of little interest, we are interested, but overbooked.  We are 1.5 developer doing the job of 3-5 developers on a product that is _lauched_ but not shipping for another 2 weeks. Crunch time! 

Honestly, It may be another week or three before we get around to grabbing pull requests because we are effectively DDOS'd out of action by updates needed for a smooth release.  

Thanks for contributing, and we likely will roll in your changes once we get back to a sane place.

**Comment by derrickoswald** [comment]
Yeah, I saw the dualstruder video (I assume that's what your working on based on the code changes), so I can imagine the pressure at this point.

When you're not so snowed, maybe you can explain the workflow for contributors that would make your life easier.I've deleted my original fork and created a new one with just the germane change. But since I'm new to GIT I'm not sure if that works for you. See pull #261 https://github.com/makerbot/ReplicatorG/pull/261.

**Pull request closed without merging**
