### PR TITLE
5D RepRap driver - manual extrude improvements

### PR DESCRIPTION
**Pull request by D1plo1d**
Hey Makerbot,

I've been doing some work on the manual extrude aspect of the control panel. I wasn't too happy with how glitchy my initial implementation was in terms of ui responsiveness so I re-factored it until it worked easily and simply.

Try it out on any 5D RepRap, you should see a fairly noticeable difference in gui responsiveness for manual extrude and temperature readings.

This is merged with the latest Makerbot head so it should be an easy pull :)

Cheers,
Rob

### CODE REVIEW

**Comment by koenkooi** [comment]
The 31a5f46 commit has a lot more changes (e.g. skeinforge profiles) than the commit messages says. Was that intentional?

**Comment by D1plo1d** [comment]
hmm, no it was not. It appears to just be a whole bunch of default values that have been added. I haven't been working on those since my last commit so it should be fine just to push as is.

That said there will be an update for mendel skeinforge settings coming in next week courtesy of Paul once I get a chance to test them out so these will all be overwritten at that point anyways.

**Comment by D1plo1d** [comment]
Don't bother pulling this now. I'm keeping 5D up to date with the makerbot master fairly regularly and will push it back once I have tested it on a few more firmwares and updated the skienforge settings.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Pull request closed without merging**
