### PR TITLE
Feature 5d checksums (missing files fixed)

### PR DESCRIPTION
**Pull request by D1plo1d**
This patch includes:
- Significantly more reliable RepRap connection sequence
- RepRap 5D driver checksums + line numbers
- RepRap 5D driver bad line resends (on checksum error)
- Machines.xml axis endstop definitions

update: fixed the missing files and various problems in this fork should be more stable and contain all files now.

### CODE REVIEW

**Comment by kintel** [comment]
I filtered out some mis-commits (lots of skeinforge preferences), and removed the serial port locking code, but I've merged and pushed the rest.
Feel free to explain what the serial locking code was good for.

**Comment by D1plo1d** [comment]
(sorry, needed to reopen to comment)

Serial Locking: used to allow manual extruder control; 5D Gcode has no way to turn the extruder on and leave it running so a second thread is used to send a constant supply of G1 E100 commands until the extruder is turned off. Without serial locking you will get weird things happening when both threads try to write to serial at the same time (out of order line number, just in general unpredictable behavior). I thought it could be useful in the serial class for future multithreaded serial stuff but it could work just as well in the reprap 5d driver.

Skeinforge Settings: These settings are for Mendel RepRaps, I'd wanted to have them included in ReplicatorG like Makerbot's so that we can make them better as a community and make RepRap work out of the box like Makerbot does. I'm testing these settings a Mendel and Paul is testing on another. I forgot to mention them in the pull request (my bad!).

**Comment by D1plo1d** [comment]
Re:SerialLocking, I take that back.. it needs to be in the SerialDriver to gaurentee the serial port isn't closed half way through sending a command.

Also thanks for the merge, I missed that point in my first comment, but it's awesome that this will end up in future versions of RepG!

**Comment by kintel** [comment]
OK, good points. I've merged both.

**Comment by D1plo1d** [comment]
awesomes, thanks Kintel!

**Pull request closed without merging**
