### PR TITLE
Fix man extruder speed default

### PR DESCRIPTION
**Pull request by ErikDeBruijn**
Please see if this commit is helpful. I've tested it to work fine.

https://github.com/ErikDeBruijn/ReplicatorG-Erik5D/commit/67e3bb8dc7da867f020312c83bc2ed60c79a2686

### CODE REVIEW

**Comment by koenkooi** [comment]
This commit also seems to have a lot of unrelated commits, was that intended?

**Comment by ErikDeBruijn** [comment]
Just the commit should just contain the functionality as described in the title. But you shouldn't merge my entire branch :S
I'm still trying to figure out how to make clean contributions with git... It seems I have to make a separate branch for every feature?

**Comment by phooky** [comment]
Hi Erik;

Can you please limit the range of this pull request to just the feature?  I'm having a really hard time merging this.

**Comment by phooky** [comment]
(See this URL for more info: http://help.github.com/pull-requests/
Specifically the bit about changing the commit range.)

**Comment by phooky** [comment]
Okay, I just spent about an hour doing an epic, messy merge.  Let's start doing features in branches from now on.  I'm still not sure master is using the right version of reprap5ddriver; could you check head and make sure it's good?

I'm hoping to do a release this week if I can tie all the loose threads together.

**Pull request closed without merging**
