### PR TITLE
Skeinforge 43, and Dimension-based Print-O-Matic

### PR DESCRIPTION
**Pull request by giseburt**
Since Skeinforge 43 doesn't have Reversify, I made Print-O-Matic work with Dimension, as it should have all along. :)

The Old behavior is unaffected.

### CODE REVIEW

**Comment by FarMcKon** [comment]
Dude, awesome pull suggestion. However I'm going to want to get SF 44, instead of brining in 43.   Can you make just a pull requst for Bookends (8ee7976), and the you (or someone else) can push SF 44 in? 

Also, I've not looked at the prelim Print-O-Matic 5d stuff much. If you want to make a pull just for that, I'll probably roll that into a 5d branch for now instead....

**Comment by giseburt** [comment]
I'll port the bookends change to 44, and pull again. I'll also ask
Enrique to add it to 45.

  -Rob

On Oct 12, 2011, at 4:08 PM, Far McKon
reply@reply.github.com
wrote:

**Comment by FarMcKon** [comment]
Hey. Ted (new software dude) just ported in 44. I hope that is the latest and greatest. We have not tested 44's profiles, so it's experimental for now. I'll send you a note to check it out/pull it.

**Comment by giseburt** [comment]
I'll take a look as soon as I can.

I also have a few more UI things to submit too...

  -Rob

On Oct 21, 2011, at 12:14 PM, Far McKon
reply@reply.github.com
wrote:

**Pull request closed without merging**
