### PR TITLE
Feature: Set debug level from CLI

### PR DESCRIPTION
**Pull request by ErikDeBruijn**
You could cherry-pick 7995ea6 if you like.

The debug level can now be set via the commandline ([--debug [level]]) + small CLI help.

Since there's now more differentiation in log levels (many info stuff is now "fine") it's now valuable to differentiate debuggers from everyday users.

Would checking a .replicatorg/debug.txt file be appropriate too? This would not require you type it every time? Also, perhaps the ant target could be changed?

### CODE REVIEW

**Comment by koenkooi** [comment]
There are 3 unrelated commits in this pull request, was that intended?

**Comment by ErikDeBruijn** [comment]
@Koenkooi: So how do I do a pull request for just one commit?

**Comment by koenkooi** [comment]
When you click "pull request" there's a "change commits"  buttons where you can edit the range. The editor isn't really intuitive, so having a (rebased) branch per feature is still the easiest way to get a nice pull request.

**Comment by phooky** [comment]
Merged.  Thanks!

**Pull request closed without merging**
