### PR TITLE
Add skeinforge 40 support

### PR DESCRIPTION
**Pull request by giseburt**
There's no profiles yet, but at least it works. I also added the patch for skeinforge that makes it work.

### CODE REVIEW

**Comment by koenkooi** [comment]
You might want to include https://github.com/koenkooi/ReplicatorG/commit/896c28788f371acbebba7b60c188b527823aea79 as well to avoid some confusion

**Comment by giseburt** [comment]
Doh! Missed that. I'll put that in tomorrow.

  -Rob

On Mar 31, 2011, at 2:18 AM, koenkooi
reply@reply.github.com
wrote:

**Comment by giseburt** [comment]
I included Koen's fixes in that last commit. Thanks Koen!

I also caught that the Raft option name has changed...

**Comment by koenkooi** [comment]
and outline has been 'replaced' with skirt, so one less thing to patch in for repG. And for people using dimension: it changed from output steps/mm to input steps/mm, so beware!

**Pull request merged**
